# Page settings

baseURL = "http://vishrut.sg/cv"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en"
theme = "hugo-devresume-theme"
title = "cv"

[params]
author = "CowboySmall"
description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

primaryColor = "#7ABAFF"
textPrimaryColor = "#292929"


[params.profile]
avatar = "vishrutsingh.png"
enable = true
name = "Vishrut Singh"

[params.contact]
enable = true
location = "India"

[[params.contact.list]]
icon = "fas fa-phone-square"
text = "+91 7357337667"
url = "tel:#"
[[params.contact.list]]
icon = "fas fa-envelope-square"
text = "bisrut.singh@gmail.com"
url = "mailto:#"
[[params.contact.list]]
icon = "fab fa-github-square"
text = "Vishrut Singh"
url = "//github.com/vishrutsingh"
[[params.contact.list]]
icon = "fab fa-linkedin"
text = "Vishrut Singh"

[params.skills]
enable = true

[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "Rust/Go"
[[params.skills.list.items]]
details = "Nix/Hugo"
[[params.skills.list.items]]
details = "JavaScript/Typescript"
[[params.skills.list.items]]
details = "MongoDB/MySQL"
[[params.skills.list.items]]
details = "Cosmos-sdk/Cosmwasm/Eth-VM"


[[params.skills.list]]
title = "Professional"
[[params.skills.list.items]]
details = "Effective communication"
[[params.skills.list.items]]
details = "Team player"
[[params.skills.list.items]]
details = "Strong problem solver"
[[params.skills.list.items]]
details = "Good time management"


[params.education]
enable = true

[[params.education.list]]
dates = "2016 - 2021"
degree = "BEng in Software & Electronics (First Class)"
university = "University of Glasgow"


[params.awards]
enable = false

[[params.awards.list]]
body = "UiPath - Advanced RPA Trainee Award"
date = "2019"


[params.languages]
enable = true

[[params.languages.list]]
level = "Native"
name = "English"
[[params.languages.list]]
level = "Native"
name = "Hindi"


[params.interests]
enable = true

[[params.interests.list]]
name = "Climbing"
[[params.interests.list]]
name = "Running"
[[params.interests.list]]
name = "Music Production"
[[params.interests.list]]
name = "Travelling"


[params.summary]
enable = true
#text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."
text = "I am Vishrut, a Software Engineer with over 2 years of experience in blockchain development. I am highly dedicated, proactive, and motivated to deliver innovative solutions, both independently and as part of a team. Committed to continuous learning and knowledge sharing, I regularly create blogs and tutorials to educate and support newcomers in the blockchain community. My hands-on approach, attention to detail, and passion for emerging technologies drive me to consistently achieve my goals."

[params.experience]
enable = true

[[params.experience.list]]
title = "Freelance Blockchains Developer"
company = "Blockchains"
dates = "October 2023 - February 2024"
[[params.experience.list.items]]
details = "Responsible for deploying and testing smart contracts on the Etherium network and documenting the testnet validator institutions."
[[params.experience.list.items]]
details = "Porting Eth contracts to Cosmos ecosystem, namely the ENS based contracts." 
[[params.experience.list.items]]
details = "Testing deployments on EVM(Eth-VM) to develop a workflow on cosmos ecosystem that can handle upto 100 validators per chain. Designing workflows to deploy smart contracts on various native chains." 
[[params.experience.list.items]]
details = "Documenting & writing articles about the latest tech in the ecosystem." 

[[params.experience.list]]
title = "Blockchain Developer"
company = "Persistence One"
dates = "December 2021 - October 2022"
[[params.experience.list.items]]
details = "Responsible for developing & testing smart contracts on the chain. Developing new workflows to integrate APIs and packages which would aid our chain become a smarth contract enabled chain in the ecosystem."
[[params.experience.list.items]]
details = "Integrating other chains and Managing Airdrops to stakers in our ecosystem."
[[params.experience.list.items]]
details = "Developed on-chain contract and workflow for our chain to enable Smart Contract usage." 
[[params.experience.list.items]]
details = "Supervised a team effort to integrate cross chain Token trasnfer for our token from Etherium to Terra & Anchor chain through our native chain on cosmos ecosystem."
[[params.experience.list.items]]
details = "Worked with a small team in the cosmos ecosystem, developing new tech and tutorials for users of CosmJS."
[[params.experience.list.items]]
details = "Setup Kubernetes for testnet and helped with testing multi-chain smart contracts."
[[params.experience.list.items]]
details = "Integrated Telescope into PersistenceJS."
[[params.experience.list.items]]
details = "Conducted monthly Airdrops to stakers in our ecosystem." 

[[params.experience.list]]
title = "Scrum Master"
company = "Vilo Sky"
dates = "October 2020 - March 2021"
[[params.experience.list.items]]
details = "Responsible for communication with client and the team to get a clear idea of what is needed and keep a weekly diary to maintain the progress of the team and additional notes to keep individual contribution."
[[params.experience.list.items]]
details = "Coached a team of 5 students to develop a website, which provides a platform for coaching and consultancy services for women."
[[params.experience.list.items]]
details = "Helped the team understand agile practices and tailored a software development process that works for the client & team."

[[params.experience.list]]
title = "Lab Demonstrator"
company = "University of Glasgow"
dates = "September 2020 - March 2021"
[[params.experience.list.items]]
details = "Coordinated 2 teams of 4 - 5 students to present and develop their website idea under the web app development course." 
[[params.experience.list.items]]
details = "Demonstrated a lab group of 10-11 students in an online environment and helped them understand concepts about data structures, algorithms and web app development."

[[params.experience.list]]
title = "Software Intern"
company = "Access Health Digital"
dates = "April 2020 - August 2020"
[[params.experience.list.items]]
details = "Interned as software developer in a non-profit software development company, focusing on digital health software services based on microservice architecture using Spring Boot." 
[[params.experience.list.items]]
details = "Microservices would then be used by medical systems in the country to record and maintain computer readable medical nomenclature such as medicen, diagnosis & treatments. I was also responsible for outreach to medical institutions asking to integrate systematic nomenclature in the education system."
[[params.experience.list.items]]
details = "Responsible for Cloud Gateway Server & Spring development and maintenance."
[[params.experience.list.items]]
details = "Conducted additional research in integrating micro service architecture with HAPI FHIR namespace server."
[[params.experience.list.items]]
details = "Participated in medical university outreach and collaboration opportunities."

[[params.experience.list]]
title = "Software Engineering Intern"
company = "Cevitr Inc."
dates = "June 2019 - August 2019"
[[params.experience.list.items]]
details = "Interned as an automated process developer,focusing on RPA(Robotic Process Automation) and maintaining the digital automated work bot. RPA agent would perform workflows that a person would take a lot of time to."
[[params.experience.list.items]]
details = "This agent would help the companies cut down their costs upto 30% for maintainence of these records."
[[params.experience.list.items]]
details = "Designing automation processes based on computer vision,that increase the efficiency of various tasks by many folds."

[[params.experience.list]]
title = "University of Glasgow Industrial Work"
company = "Craft prospect"
dates = "September 2018 - March 2019"
[[params.experience.list.items]]
details = "Working in a team of 4 students,to develop an arcade machine for a Machine learning based space game. The company would end up using this machine to demonstrate their space capabilities to clients in confrences and various meetings."
[[params.experience.list.items]]
details = "Demonstrated the project to clients which provided a better understanding about the use of ML in satellite imaging." 
[[params.experience.list.items]]
details = "Designed and made the Arcade machine using 3D Printers" 
[[params.experience.list.items]]
details = "Collected cloud coverage satalite data to train a model using OpenCV." 


[params.projects]
enable = false 

[[params.projects.list]]
meta = "Open Source"
tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
title = "Project Lorem Ipsum"

[params.information]
enable = true

[[params.information.list]]
title = "Certification"
[[params.information.list.items]]
details = "2019 · UIPath - Advanced RPA Certificate"

[[params.information.list]]
details = "Climbing, Snowboarding, Photography, Travelling"
title = "Interests"


[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
title = "Vishrut Singh"
url = "//github.com/vishrutsingh"
[[params.social.list]]
icon = "fab fa-linkedin"
title = "Vishrut Singh"
url = "//linkedin.com/in/bisrut"
[[params.social.list]]
icon = "fab fa-twitter-square"
title = "@bisruut"
url = "//twitter.com/bisruut"
