# Page settings

baseURL = "http://vishrut.sg/cv/honest"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en"
theme = "hugo-devresume-theme"
title = "cv"
publishDir = "public/honest"
[params]
  author = "CowboySmall"
  description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

  primaryColor = "#7ABAFF"
  textPrimaryColor = "#292929"


[params.profile]
  avatar = "vishrutsingh.png"
  enable = true
  name = "Vishurt Singh"
  tagline = "Blockchain Developer"


[params.contact]
  enable = true
  location = "India"

[[params.contact.list]]
  icon = "fas fa-phone-square"
  text = "+91 7357337667"
  url = "tel:#"
[[params.contact.list]]
  icon = "fas fa-envelope-square"
  text = "bisrut.singh@gmail.com"
  url = "mailto:#"
[[params.contact.list]]
  icon = "fas fa-globe"
  text = "https://vishrutsingh.github.io/"
  url = "#"


[params.skills]
  enable = true

[[params.skills.list]]
  title = "Technical"
[[params.skills.list.items]]
  details = "Rust/Go"
[[params.skills.list.items]]
  details = "JavaScript/Typescript"
[[params.skills.list.items]]
  details = "Node.js/Nix"
[[params.skills.list.items]]
  details = "MongoDB/MySQL"
[[params.skills.list.items]]
  details = "Object-oriented design"
[[params.skills.list.items]]
  details = "Blockchain/Cosmos-sdk/Cosmwasm"


[[params.skills.list]]
  title = "Professional"
[[params.skills.list.items]]
  details = "Effective communication"
[[params.skills.list.items]]
  details = "Team player"
[[params.skills.list.items]]
  details = "Strong problem solver"
[[params.skills.list.items]]
  details = "Good time management"


[params.education]
  enable = true

[[params.education.list]]
  dates = "2016 - 2021"
  degree = "BEng in Computer Science"
  university = "University of Glasgow"


[params.awards]
  enable = false

[[params.awards.list]]
  body = "UiPath - Advanced RPA Trainee Award"
  date = "2019"


[params.languages]
  enable = true

[[params.languages.list]]
  level = "Native"
  name = "English"
[[params.languages.list]]
  level = "Native"
  name = "Hindi"


[params.interests]
  enable = true

[[params.interests.list]]
  name = "Climbing"
[[params.interests.list]]
  name = "Running"
[[params.interests.list]]
  name = "Music Production"
[[params.interests.list]]
  name = "Travelling"


[params.summary]
  enable = true
  #text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."
  text = "I'm Vishrut, an Indian Software Engineer with 1+ years of experience developing Blockchains. I am a dedicated, hardworking, ambitious person that gets things done, both on my own initiative and within a team. I enjoy challenges and I am not afraid of getting my hands dirty. Because knowledge sharing matters to me, I enjoy spending non negligible time writing blogs and tutorials that I share with new comers to the Blockchain community."

[params.experience]
  enable = true

[[params.experience.list]]
  title = "Freelance Blockchains Developer"
  company = "Cosmos Ecosystem"
  dates = "October 2023 - February 2024"
  details = "I had a lot of trouble trying to find my way through this process of freelancing. I had a lot of knowledge but when i worked i found out i was very medicore at developing contracts. the hardest thing that i encountered was porting contracts form a different chain. It still is not easy as people might think. Leads me to think that if most blockchains work the same why not have a general configuration and generate based on a framework, but as i found out this is an extremely comlex problem. I still continue to consult people, but i am loosing interest in making genereal soulutions to these types of porblems."
  

[[params.experience.list]]
  company = "Persistence One"
  dates = "December 2021 - October 2022"
  details = "This was the greatest opportunity i could have ever had because during Uni i was extremely interested in blockchain and somehow the stars alligned and i was able to get a job in the field i wanted to work in, never mind it was state of the art work during that point. I got to learn a lot about how a Professional Professional env works and how open the blockchain community is. This lead me to believe you can build anythig, and even now you can! It is a bit boring to try and learn things as you go because things repeat but in a different language or framework, but you can do what ever you want. Who knows where your idea might be used."
  title = "Blockchain Developer"

[[params.experience.list]]
  company = "Vilo Sky"
  dates = "October 2020 - March 2021"
  details = "This is a job i took on cuz i needed money, but as all jobs thats how it works. I personally liked this job cuz you can make your experiences as an example and try to teach people. And teaching people is an awesome thing of you like it."
  title = "Scrum Master"

[[params.experience.list]]
  company = "University of Glasgow"
  dates = "September 2020 - March 2021"
  details = "This was a shitshow b/w the teacher and the demonstrator, espesilly or unluckily for me as i was demonstrating absolute beginners. Worst part was trying to not teach and jsut stand there and give no instructions. Problems were very simple but had a trick that i was not supposed to hint. It was my first experience in dealing with a lower and a higher herarchy."
  title = "Lab Demonstrator"

[[params.experience.list]]
  company = "Access Health Digital"
  dates = "April 2020 - August 2020"
  details = "Some how even during the Pandemic i managed to keep my whits about and work through this project. I was learning a shit ton, and as my parents are both doctors i had a pretty good idea as to what this company was trying to achieve. So i was atached to the cause and still am."
  title = "Software Intern"

[[params.experience.list]]
  company = "Cevitr Inc."
  dates = "June 2019 - August 2019"
  details = "This was my official first software jovb, through neportsm ofc. But i manged to do v. good. It didnt have any revolutionary tech but it was fun at some points as i was the only developer they had so i had to work a lot. Hence, it might have been a type 2 fun but in the end it was fun."
  title = "Software Engineering Intern"
[[params.experience.list.items]]
  details = "Designing automation processes based on computer vision,that increase the efficiency of various tasks by many folds."

[[params.experience.list]]
  company = "Craft prospect"
  dates = "September 2018 - March 2019"
  details = "This was a shit show again but the company was very good to work with and as a client they might have been perfect as there were no customers for the project. I had to learn a lot during this project but it was fun in the end and we made an arcade machine that uses AI, do i need to say more."
  title = "University of Glasgow Industrial Work"


[params.projects]
  enable = false 

# [[params.projects.list]]
#   meta = "Open Source"
#   tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
#   title = "Project Lorem Ipsum"

[params.information]
  enable = true

[[params.information.list]]
  title = "Certification"
[[params.information.list.items]]
  details = "2019 · UIPath - Advanced RPA Certificate"

[[params.information.list]]
  details = "Climbing, Snowboarding, Photography, Travelling"
  title = "Interests"


[params.social]
  enable = true

[[params.social.list]]
  icon = "fab fa-github-square"
  title = "Vishrut Singh"
  url = "//github.com/vishrutsingh"
[[params.social.list]]
  icon = "fab fa-linkedin"
  title = "Vishrut Singh"
  url = "//linkedin.com/in/bisrut"
[[params.social.list]]
  icon = "fab fa-twitter-square"
  title = "@bisruut"
  ur = "//twitter.com/bisruut"
